version: "3.8"
name: about-spring-security

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-security
    ports:
      - "33063:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassw0rd
      MYSQL_DATABASE: security
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

networks:
  default:
    name: about-spring-security-network