version: "3.8"
name: springboot-db-performance

services:
  mysql5:
    image: mysql:5.7
    container_name: mysql5
    platform: linux/amd64
    ports:
      - "10000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassw0rd
      MYSQL_DATABASE: inspect
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  mysql8:
    image: mysql:8.4
    container_name: mysql8
    ports:
      - "10001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassw0rd
      MYSQL_DATABASE: inspect
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    volumes:
      - ./mysql8/conf:/etc/mysql/conf.d
      - ./mysql8/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  mysql9:
    image: mysql:9.1
    container_name: mysql9
    ports:
      - "10002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassw0rd
      MYSQL_DATABASE: inspect
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  postgres17:
    image: postgres:17.2
    container_name: postgres17
    ports:
      - "10003:5432"
    environment:
      POSTGRES_DB: inspect
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passw0rd
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "10004:27017"
    environment:
      MONGO_INITDB_DATABASE: inspect
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

networks:
  default:
    name: db-performance-network