version: "3.8"
name: springboot-db-performance

services:
  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    ports:
      - "10010:9104"
    environment:
      DATA_SOURCE_NAME: "exporter:passw0rd@(mysql8:3306)/"
    command:
      - "--mysqld.username=exporter:passw0rd"
      - "--mysqld.address=mysql8:3306"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "10020:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - mysqld_exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "10030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

networks:
  default:
    name: db-performance-network