feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        # NONE: ???? ??, ???
        # BASIC: ?? ???? URI? ?? ??? ????? ???
        # HEADERS: ??? ?? ??? ?? ??? ???? ??
        # FULL: ??? ??? ?? ??? ??, ?? ???? ??


logging:
  level:
    com.raynor.demo.aboutfeign.app.http.OutSideAPI: debug
    com.raynor.demo.aboutfeign.app.http.DynamicUrlAPI: debug

spring:
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 5000
        ok-http:
          read-timeout: 5s