feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
        # NONE: ???? ??, ???
        # BASIC: ?? ???? URI? ?? ??? ????? ???
        # HEADERS: ??? ?? ??? ?? ??? ???? ??
        # FULL: ??? ??? ?? ??? ??, ?? ???? ??

logging:
  level:
    com.raynor.demo.aboutfeign.app.http.OutSideAPI: debug
    com.raynor.demo.aboutfeign.app.http.DynamicUrlAPI: debug
