version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "sanggi-wjg"
    groups: # 관련 액션들을 하나의 PR로 묶기
      actions:
        patterns:
          - "*"
