version: "3.8"
name: springboot-db-performance

services:
  mysql5:
    image: mysql:5.7
    container_name: mysql5
    platform: linux/amd64
    ports:
      - "10000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassw0rd
      MYSQL_DATABASE: inspect
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
  mysql8:
    image: mysql:8.4
    container_name: mysql8
    ports:
      - "10001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassw0rd
      MYSQL_DATABASE: inspect
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
  mysql9:
    image: mysql:9.1
    container_name: mysql9
    ports:
      - "10002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassw0rd
      MYSQL_DATABASE: inspect
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd

  postgres17:
    image: postgres:17.2
    container_name: postgres17
    ports:
      - "10003:5432"
    environment:
      POSTGRES_DB: inspect
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passw0rd

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "10004:27017"
    environment:
      MONGO_INITDB_DATABASE: inspect
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: passw0rd

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: "exporter:passw0rd@(mysql8:3306)/"
    command:
      - "--mysqld.username=exporter:passw0rd"
      - "--mysqld.address=mysql8:3306"
    depends_on:
      - mysql8

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./grafana/prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - mysql8

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - mysql8
      - postgres17

networks:
  default:
    name: db-performance-network