version: "3.8"
name: springboot-db-performance

services:
  mysql5:
    image: mysql:5.7
    container_name: mysql5
    platform: linux/amd64
    ports:
      - "10000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassw0rd
      MYSQL_DATABASE: inspect
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
  mysql8:
    image: mysql:8.4
    container_name: mysql8
    ports:
      - "10001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassw0rd
      MYSQL_DATABASE: inspect
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
  mysql9:
    image: mysql:9.1
    container_name: mysql9
    ports:
      - "10002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassw0rd
      MYSQL_DATABASE: inspect
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd


networks:
  default:
    name: db-performance-network