global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rds'
    static_configs:
      - targets: [ 'mysqld_exporter:9104' ]
        labels:
          group: 'mysql'
          instance: 'mysql8'
