apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: qos-demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'spring-boot'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['qos-guaranteed:8080']
            labels:
              group: 'spring-boot-application'
          - targets: ['qos-burstable:8080']
            labels:
              group: 'spring-boot-application'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: qos-demo
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.retention.time=1h"
      volumes:
        - name: config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: qos-demo
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090