services:
  my-nginx:
    image: nginx:latest
    container_name: my-nginx
    networks: 
      - about-nginx-network
    ports:
      - "80:80"
      - "443:443/tcp"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/html:/home/html:ro
  
  # https://hub.docker.com/r/macbre/nginx-http3
  my-nginx-http3:
    image: macbre/nginx-http3:latest
    container_name: my-nginx-http3
    networks: 
      - about-nginx-network
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./nginx/conf_http3.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/html:/home/html:ro

networks:
  about-nginx-network:
    name: about-nginx-network
    driver: bridge