services:
  local-nginx:
    image: nginx:latest
    container_name: local-nginx
    networks: 
      - local-nginx-network
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/html:/home/html

networks:
  local-nginx-network:
    name: local-nginx-network
    driver: bridge