### Health Check
GET http://localhost:8210/iam

### Actuator Health
GET http://localhost:8201/actuator/health

### Prometheus Metrics
GET http://localhost:8201/actuator/prometheus

###############################################################

### Heap Stress
GET http://localhost:8210/stress/heap?sizeInMB=1&delayMs=100&repeat=100

### Direct Stress
GET http://localhost:8211/stress/direct?sizeInMB=1&delayMs=100&repeat=100

### Native Stress
GET http://localhost:8212/stress/native?sizeInMB=1&delayMs=100&repeat=100

### Clear - Pod
GET http://localhost:8210/stress/clear

### Clear - Pod
GET http://localhost:8211/stress/clear

### Clear - Pod
GET http://localhost:8212/stress/clear
