global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'agt-app:8080' ]
        labels:
          group: 'application'
          instance: 'spring-boot-instance'
