### Email Signup
POST http://localhost:8080/api/v1/accounts/email-signup
Content-Type: application/json

{
  "email": "user@dev.com",
  "name": "Dev User",
  "password": "n00b"
}

### Email Signin: User
POST http://localhost:8080/api/v1/accounts/email-login
Content-Type: application/json

{
  "email": "user@dev.com",
  "password": "n00b"
}

### Email Signin: Admin
POST http://localhost:8080/api/v1/accounts/email-login
Content-Type: application/json

{
  "email": "admin@dev.com",
  "password": "p@ssw0rd"
}

### Users ME
GET http://localhost:8080/api/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBkZXYuY29tIiwidXNlcklkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzM2NjkzMDE3LCJleHAiOjE3MzY2OTY2MTd9.7JXyp6Yh_ev2_mPyn4rv3c-qRGZxw__MkmZTeo0gqzBt_TJqAYxiq88iOdfUZgoNXQyoMrmg9mhrQ8nqEzV6lg
