### POST Users
POST http://localhost:8080/users
Content-Type: Application/json

{
  "email": "abc",
  "name": "def",
  "age": -1
}

### Get User 0
GET localhost:8080/users/0

### Get User 1
GET localhost:8080/users/1
