name: springboot-boiler

services:
  mysql:
    image: mysql:8.0
    container_name: boiler-mysql
    ports:
      - "6500:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=boiler
      - MYSQL_USER=boiler
      - MYSQL_PASSWORD=boiler1234
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M

  redis:
    image: redis:latest
    container_name: boiler-redis
    ports:
      - '6501:6379'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
